/**
 * Static PDF generation for dispute evidence.
 *
 * Hard rules:
 * - Static templates only. No LLM/generative narrative.
 * - Merchant cannot inject arbitrary paragraphs at runtime — every text field
 *   in the PDF comes from a strictly-typed schema (lib/evidence/schemas.ts).
 * - Each PDF embeds a SIGNED manifest as an attachment. Manifest contains:
 *   adapter name+version, dispute ID, charge ID, reason code, source data
 *   field hashes, adapter response SHA-256, PDF SHA-256, signing key ID,
 *   created timestamp, CE 3.0 eligibility result.
 *
 * Signature: Ed25519 detached signature over canonical JSON of the manifest.
 * DISPUTE_SIGNING_KEY env var holds the 32-byte seed as 64 hex chars.
 *
 * NOTE: README does NOT claim the PDF itself is PAdES-signed. Only the
 * embedded manifest attachment is signed.
 */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import * as ed from '@noble/ed25519';
import { createHash } from 'node:crypto';
import { canonicalJson, sha256Hex } from '../audit/log';
import type { CustomerEvidenceBundle } from '../evidence/schemas';
import type { Ce3EligibilityResult } from './../evidence/ce3';

export interface GeneratePdfInput {
  disputeId: string;
  stripeDisputeId: string;
  stripeChargeId: string;
  reasonCode: string;
  bundle: CustomerEvidenceBundle;
  bundleSha256: string;
  ce3Eligibility: Ce3EligibilityResult | null;
}

export interface GeneratePdfResult {
  pdfBytes: Uint8Array;
  pdfSha256: string;
  manifest: ManifestPayload;
  manifestSignature: string;
  signingKeyId: string;
}

export interface ManifestPayload {
  schemaVersion: '1';
  adapterName: string;
  adapterVersion: string;
  disputeId: string;
  stripeDisputeId: string;
  stripeChargeId: string;
  reasonCode: string;
  bundleSha256: string;
  pdfSha256: string;
  ce3Eligibility: { qualified: boolean; reasons: string[] } | null;
  createdAt: string;
  signingKeyId: string;
}

export async function generateDisputePdf(input: GeneratePdfInput): Promise<GeneratePdfResult> {
  const seedHex = process.env.DISPUTE_SIGNING_KEY;
  if (!seedHex || !/^[0-9a-f]{64}$/i.test(seedHex)) {
    throw new Error('DISPUTE_SIGNING_KEY must be 64 hex chars (32-byte Ed25519 seed). Generate with: node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))"');
  }
  const seed = Buffer.from(seedHex, 'hex');
  const publicKey = await ed.getPublicKeyAsync(seed);
  const signingKeyId = sha256Hex(Buffer.from(publicKey)).slice(0, 16);

  // Build PDF
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontMono = await pdf.embedFont(StandardFonts.Courier);

  let page = pdf.addPage([612, 792]); // US Letter
  let y = 760;
  const margin = 48;
  const lineHeight = 14;

  const draw = (text: string, opts?: { font?: 'normal' | 'bold' | 'mono'; size?: number; color?: [number, number, number] }) => {
    if (y < 60) {
      page = pdf.addPage([612, 792]);
      y = 760;
    }
    const f = opts?.font === 'bold' ? fontBold : opts?.font === 'mono' ? fontMono : font;
    const size = opts?.size ?? 10;
    const c = opts?.color ?? [0.07, 0.10, 0.20];
    page.drawText(text, { x: margin, y, font: f, size, color: rgb(c[0]!, c[1]!, c[2]!) });
    y -= size + 4;
  };
  const blank = () => { y -= lineHeight; };
  const rule = () => {
    page.drawLine({
      start: { x: margin, y: y + 2 },
      end: { x: 612 - margin, y: y + 2 },
      thickness: 0.5,
      color: rgb(0.6, 0.6, 0.7),
    });
    y -= 8;
  };

  // Header
  draw('DISPUTE EVIDENCE', { font: 'bold', size: 16 });
  draw(`Generated by dispute-defender · ${new Date().toISOString()}`, { font: 'mono', size: 8, color: [0.4, 0.45, 0.55] });
  blank(); rule();

  // Dispute identifiers
  draw('DISPUTE', { font: 'bold', size: 11 });
  draw(`Stripe Dispute ID:  ${input.stripeDisputeId}`, { font: 'mono', size: 9 });
  draw(`Stripe Charge ID:   ${input.stripeChargeId}`, { font: 'mono', size: 9 });
  draw(`Network reason:     ${input.reasonCode}`, { font: 'mono', size: 9 });
  blank(); rule();

  // Customer
  draw('CUSTOMER', { font: 'bold', size: 11 });
  draw(`Stripe Customer ID: ${input.bundle.customer.stripeCustomerId ?? '(not available)'}`, { font: 'mono', size: 9 });
  draw(`Email:              ${input.bundle.customer.customerEmailAddress ?? '(not available)'}`, { font: 'mono', size: 9 });
  draw(`Account ID:         ${input.bundle.customer.customerAccountId ?? '(not available)'}`, { font: 'mono', size: 9 });
  draw(`Signup:             ${input.bundle.customer.signupTimestamp?.toISOString() ?? '(not available)'}`, { font: 'mono', size: 9 });
  blank(); rule();

  // Disputed transaction
  draw('DISPUTED TRANSACTION', { font: 'bold', size: 11 });
  draw(`Timestamp:          ${input.bundle.disputedTransaction.transactionTimestamp.toISOString()}`, { font: 'mono', size: 9 });
  draw(`Type:               ${input.bundle.disputedTransaction.merchandiseOrServices}`, { font: 'mono', size: 9 });
  draw(`Description:        ${input.bundle.disputedTransaction.productDescription}`, { font: 'mono', size: 9 });
  draw(`IP at purchase:     ${input.bundle.disputedTransaction.customerPurchaseIp ?? '(not available)'}`, { font: 'mono', size: 9 });
  draw(`Device fingerprint: ${input.bundle.disputedTransaction.customerDeviceFingerprint ?? '(not available)'}`, { font: 'mono', size: 9 });
  draw(`Device ID:          ${input.bundle.disputedTransaction.customerDeviceId ?? '(not available)'}`, { font: 'mono', size: 9 });
  blank(); rule();

  // Prior undisputed transactions
  draw('PRIOR UNDISPUTED TRANSACTIONS', { font: 'bold', size: 11 });
  if (input.ce3Eligibility?.qualified && input.ce3Eligibility.selectedPriors.length === 2) {
    for (const p of input.ce3Eligibility.selectedPriors) {
      draw(`Charge:             ${p.stripeChargeId}`, { font: 'mono', size: 9 });
      draw(`Timestamp:          ${p.transactionTimestamp.toISOString()}`, { font: 'mono', size: 9 });
      draw(`Description:        ${p.productDescription}`, { font: 'mono', size: 9 });
      draw(`IP at purchase:     ${p.customerPurchaseIp ?? '(not available)'}`, { font: 'mono', size: 9 });
      blank();
    }
  } else if (input.ce3Eligibility) {
    draw('CE 3.0 not qualified:', { font: 'mono', size: 9, color: [0.7, 0.3, 0.2] });
    for (const r of input.ce3Eligibility.reasons) {
      draw(`  · ${r}`, { font: 'mono', size: 9, color: [0.5, 0.3, 0.2] });
    }
    blank();
  } else {
    draw('Not a CE 3.0 candidate (non-Visa or non-10.4); standard evidence path.', { font: 'mono', size: 9, color: [0.4, 0.45, 0.55] });
    blank();
  }
  rule();

  // Usage timeline (deterministic, no narrative)
  draw('PRODUCT USAGE EVENTS', { font: 'bold', size: 11 });
  if (input.bundle.productUsageEvents.length === 0) {
    draw('(no usage events recorded by adapter)', { font: 'mono', size: 9, color: [0.4, 0.45, 0.55] });
  } else {
    for (const e of input.bundle.productUsageEvents.slice(0, 30)) {
      draw(`${e.timestamp.toISOString()}  ${e.eventType}${e.resourceId ? '  ' + e.resourceId : ''}`, { font: 'mono', size: 8 });
    }
    if (input.bundle.productUsageEvents.length > 30) {
      draw(`...${input.bundle.productUsageEvents.length - 30} more events (truncated for display, full list in manifest)`, { font: 'mono', size: 8, color: [0.4, 0.45, 0.55] });
    }
  }
  blank(); rule();

  // Refund policy + terms acceptance
  if (input.bundle.refundPolicy) {
    draw('REFUND POLICY', { font: 'bold', size: 11 });
    draw(input.bundle.refundPolicy.url, { font: 'mono', size: 9 });
    draw(`Content hash: ${input.bundle.refundPolicy.contentSha256}`, { font: 'mono', size: 8, color: [0.4, 0.45, 0.55] });
    blank();
  }
  if (input.bundle.termsAcceptance) {
    draw('TERMS ACCEPTANCE', { font: 'bold', size: 11 });
    draw(`Accepted at: ${input.bundle.termsAcceptance.timestamp.toISOString()}`, { font: 'mono', size: 9 });
    draw(`Terms hash: ${input.bundle.termsAcceptance.termsVersionHash}`, { font: 'mono', size: 8, color: [0.4, 0.45, 0.55] });
    blank();
  }
  rule();

  // Manifest summary footer (the actual signed manifest is embedded as JSON attachment)
  draw('MANIFEST', { font: 'bold', size: 11 });
  draw(`Adapter:        ${input.bundle.adapterName} v${input.bundle.adapterVersion}`, { font: 'mono', size: 9 });
  draw(`Adapter SHA-256: ${input.bundleSha256}`, { font: 'mono', size: 8, color: [0.4, 0.45, 0.55] });
  draw(`Signing key ID: ${signingKeyId}`, { font: 'mono', size: 8, color: [0.4, 0.45, 0.55] });
  draw(`Signed manifest attached as manifest.signed.json`, { font: 'mono', size: 8, color: [0.4, 0.45, 0.55] });

  // Generate PDF bytes (without manifest attachment) so we can hash the visual content,
  // then build manifest, sign, and re-save with attachment.
  const tempBytes = await pdf.save();
  const pdfSha256 = sha256Hex(Buffer.from(tempBytes));

  const manifest: ManifestPayload = {
    schemaVersion: '1',
    adapterName: input.bundle.adapterName,
    adapterVersion: input.bundle.adapterVersion,
    disputeId: input.disputeId,
    stripeDisputeId: input.stripeDisputeId,
    stripeChargeId: input.stripeChargeId,
    reasonCode: input.reasonCode,
    bundleSha256: input.bundleSha256,
    pdfSha256,
    ce3Eligibility: input.ce3Eligibility
      ? { qualified: input.ce3Eligibility.qualified, reasons: input.ce3Eligibility.reasons }
      : null,
    createdAt: new Date().toISOString(),
    signingKeyId,
  };

  const manifestJson = canonicalJson(manifest);
  const manifestSignature = Buffer.from(
    await ed.signAsync(Buffer.from(manifestJson, 'utf8'), seed)
  ).toString('hex');

  const signedAttachment = canonicalJson({
    manifest,
    signature: manifestSignature,
    publicKey: Buffer.from(publicKey).toString('hex'),
    algorithm: 'ed25519',
  });

  await pdf.attach(Buffer.from(signedAttachment, 'utf8'), 'manifest.signed.json', {
    mimeType: 'application/json',
    description: 'dispute-defender signed manifest (Ed25519)',
    creationDate: new Date(),
    modificationDate: new Date(),
  });

  const finalBytes = await pdf.save();

  return {
    pdfBytes: finalBytes,
    pdfSha256: sha256Hex(Buffer.from(finalBytes)),
    manifest,
    manifestSignature,
    signingKeyId,
  };
}

/** Verify a signed manifest attachment (used in tests + manifest-verification CLI). */
export async function verifyManifestSignature(payload: {
  manifest: ManifestPayload;
  signature: string;
  publicKey: string;
}): Promise<boolean> {
  const json = canonicalJson(payload.manifest);
  return ed.verifyAsync(
    Buffer.from(payload.signature, 'hex'),
    Buffer.from(json, 'utf8'),
    Buffer.from(payload.publicKey, 'hex')
  );
}

// Compatibility helper for older crypto tests that use sync sha256
export { sha256Hex };
function _shaUnused() { return createHash; }
